### ISSUE TITLE
NeXT-Server与panel初始化节点失败，通讯报错内部错误500

### ISSUE THREAD

**Issue by Celdrick** [The-NeXT-Project/NeXT-Server#57]
panel端已在.config.yaml文件正确设置mukey为123456，NeXT-Server配置如下：
panel端nginx日志：
/mod_mu/nodes/1/info?key=123456&muKey=123456 HTTP/1.1" 500 5313

`
ubuntu@ubuntu:~$ sudo /usr/local/next-server/next-server --config /etc/next-server/config.yml
NeXT-Server 0.3.8 (Next generation proxy server.) 
2024/09/26 01:42:29 Start the panel..
2024/09/26 01:42:29 Xray Core Version: 1.8.23
2024/09/26 01:42:29 Panel Start failed: request https://panel_domain.com/mod_mu/nodes/1/info failed: <!doctype html>

panic: Panel Start failed: request https://panel_domain.com/mod_mu/nodes/1/info failed: <!doctype html>

goroutine 1 [running]:
log.Panicf({0x3d6cddb?, 0x4254118?}, {0xc0001a59a8?, 0xc000cb0b40?, 0x3481680?})
        log/log.go:439 +0x65
github.com/The-NeXT-Project/NeXT-Server/panel.(*Panel).Start(0xc001213780)
        github.com/The-NeXT-Project/NeXT-Server/panel/panel.go:207 +0x485
github.com/The-NeXT-Project/NeXT-Server/cmd.run()
        github.com/The-NeXT-Project/NeXT-Server/cmd/root.go:97 +0x239
github.com/The-NeXT-Project/NeXT-Server/cmd.init.func1(0xc0001e3d00?, {0x3d40f29?, 0x4?, 0x3d40df9?})
        github.com/The-NeXT-Project/NeXT-Server/cmd/root.go:26 +0x13
github.com/spf13/cobra.(*Command).execute(0x6b93d60, {0xc000102820, 0x2, 0x2})
        github.com/spf13/cobra@v1.8.1/command.go:989 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0x6b93d60)
        github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/The-NeXT-Project/NeXT-Server/cmd.Execute(...)
        github.com/The-NeXT-Project/NeXT-Server/cmd/root.go:111
main.main()
        github.com/The-NeXT-Project/NeXT-Server/main.go:32 +0x1b3
`

**Comment by Celdrick** [comment]
panel_domain.com配置正常，已创建node1，vmess
panel_domain.com、node_domain.com已正确解析，全部直接解析未设置cdn
NeXT-Server配置如下：
```
ubuntu@slice2:~$ cat /etc/next-server/config.yml
Log:
  Level: warning # Log level: none, error, warning, info, debug 
  AccessPath: /etc/next-server/access.Log
  ErrorPath: /etc/next-server/error.log
DnsConfigPath: /etc/next-server/dns.json
RouteConfigPath: /etc/next-server/route.json
InboundConfigPath: /etc/next-server/custom_inbound.json
OutboundConfigPath: /etc/next-server/custom_outbound.json
ConnectionConfig:
  Handshake: 4 # Handshake time limit, Second
  ConnIdle: 30 # Connection idle time limit, Second
  UplinkOnly: 2 # Time limit when the connection downstream is closed, Second
  DownlinkOnly: 4 # Time limit when the connection is closed after the uplink is closed, Second
  BufferSize: 64 # The internal cache size of each connection, kB
Nodes:
  - PanelType: "sspanel-old" # Panel type: sspanel-old, nextpanel-v1(wip)
    ApiConfig:
      ApiHost: "panel_domain.com"
      ApiKey: "123456"
      NodeID: 1
      NodeType: vmess # Node type: vmess, trojan, shadowsocks, shadowsocks2022
      Timeout: 30 # Timeout for the api request
      SpeedLimit: 0 # Mbps, Local settings will replace remote settings, 0 means disable
      DeviceLimit: 0 # Local settings will replace remote settings, 0 means disable
      RuleListPath: # /etc/next-server/rulelist Path to local rulelist file
    ControllerConfig:
      ListenIP: 0.0.0.0 # IP address you want to listen
      SendIP: 0.0.0.0 # IP address you want to send pacakage
      UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
      CertConfig:
        CertMode: file #dns # Option about how to get certificate: none, file, http, tls, dns. Choose "none" will forcedly disable the tls config.
        CertDomain: "node_domain.com" # Domain to cert
        CertFile: /etc/next-server/cert/node_domain.com.cert # Provided if the CertMode is file
        KeyFile: /etc/next-server/cert/node_domain.com.key
        Provider: # alidns # cloudflare # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
        Email: #xxx@xxx.com
        DNSEnv: # DNS ENV option used by DNS provider
          # ALICLOUD_ACCESS_KEY: aaa
          # ALICLOUD_SECRET_KEY: bbb
          # CF_DNS_API_TOKEN: xxx
      EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
      DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, DNS strategy
      DisableUploadTraffic: false # Disable upload traffic to API
      DisableGetRule: false # Disable get rule
      EnableProxyProtocol: false # Only works for WebSocket and TCP
      DisableIVCheck: false # Disable IV check
      DisableSniffing: false # Disable sniffing
      AutoSpeedLimitConfig:
        Limit: 0 # Warned speed. Set to 0 to disable AutoSpeedLimit (mbps)
        WarnTimes: 0 # After (WarnTimes) consecutive warnings, the user will be limited. Set to 0 to punish overspeed user immediately.
        LimitSpeed: 0 # The speedlimit of a limited user (unit: mbps)
        LimitDuration: 0 # How many minutes will the limiting last (unit: minute)
```
